# Generated by Django 6.1.1 on 2026-10-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('inventory__gte', 0)), name='inventory_no_negativo'),
        ),
    ]
